# library

In [39]:
# Ensure numpy is installed

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [40]:
df_person = pd.read_csv('person.csv')
df_vehicle = pd.read_csv('vehicle.csv')
df_crash = pd.read_csv('vic_road_crash_data.csv')

# check missing value

In [41]:
df_person.describe()

           INJ_LEVEL  HELMET_BELT_WORN  ROAD_USER_TYPE   EJECTED_CODE
count  436360.000000     436359.000000   436360.000000  410147.000000
mean        3.251655          4.056786        2.591975       0.543327
std         0.766271          3.606979        1.319231       1.934430
min         1.000000          1.000000        1.000000       0.000000
25%         3.000000          1.000000        2.000000       0.000000
50%         3.000000          1.000000        2.000000       0.000000
75%         4.000000          9.000000        3.000000       0.000000
max         4.000000          9.000000       16.000000       9.000000

In [42]:
df_person

,ACCIDENT_NO,PERSON_ID,VEHICLE_ID,SEX,AGE_GROUP,INJ_LEVEL,INJ_LEVEL_DESC,SEATING_POSITION,HELMET_BELT_WORN,ROAD_USER_TYPE,ROAD_USER_TYPE_DESC,LICENCE_STATE,TAKEN_HOSPITAL,EJECTED_CODE
0,T20120028483,B,B,M,22-25,3,Other injury,D,1.0,2,Drivers,V,NaN,0.0
1,T20160009588,03,A,F,22-25,3,Other injury,LR,1.0,3,Passengers,NaN,NaN,0.0
2,T20190007195,A,A,M,18-21,4,Not injured,D,1.0,2,Drivers,Z,NaN,0.0
3,T20190010235,B,B,M,30-39,3,Other injury,D,1.0,2,Drivers,V,NaN,NaN
4,T20130004323,01,A,M,0-4,3,Other injury,LR,3.0,3,Passengers,NaN,N,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436355,T20250001565,02,B,F,30-39,4,Not injured,LF,1.0,3,Passengers,NaN,NaN,0.0
436356,T20200000891,B,B,M,30-39,2,Serious injury,D,1.0,2,Drivers,V,Y,0.0
436357,T20240022185,01,B,F,22-25,3,Other injury,LF,1.0,3,Passengers,NaN,N,0.0
436358,T20210024368,B,B,F,50-59,2,Serious injury,D,1.0,2,Drivers,V,Y,9.0
436359,T20250001796,B,B,M,22-25,3,Other injury,D,1.0,2,Drivers,V,N,0.0

In [43]:
df_crash.describe()

,DCA_CODE,ROAD_ROUTE_1,LATITUDE,LONGITUDE,VICGRID_X,VICGRID_Y,TOTAL_PERSONS,INJ_OR_FATAL,FATALITY,SERIOUSINJURY,...,PED_CYCLIST_5_12,PED_CYCLIST_13_18,OLD_PED_65_AND_OVER,OLD_DRIVER_75_AND_OVER,YOUNG_DRIVER_18_25,NO_OF_VEHICLES,HEAVYVEHICLE,PASSENGERVEHICLE,MOTORCYCLE,PT_VEHICLE
count,185722.000000,185637.000000,185637.000000,185637.000000,1.856370e+05,1.856370e+05,185722.000000,185722.000000,185722.000000,185722.000000,...,185722.000000,185722.000000,185722.000000,185722.000000,185722.000000,185713.000000,185713.000000,185713.000000,185713.000000,185713.000000
mean,138.790321,6527.472778,-37.716165,144.969364,2.497209e+06,2.420224e+06,2.364152,1.300336,0.017865,0.412891,...,0.009148,0.016067,0.018151,0.068102,0.299604,1.823922,0.048031,1.445418,0.143453,0.012255
std,25.986560,2993.537657,0.557105,0.800757,7.109198e+04,6.153375e+04,1.457594,0.756386,0.143918,0.622211,...,0.100276,0.130028,0.137040,0.258670,0.518907,0.747250,0.226049,0.910488,0.360426,0.111047
min,100.000000,-1.000000,-39.030830,140.966480,2.129485e+06,2.273772e+06,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,120.000000,4961.000000,-37.959026,144.833020,2.485286e+06,2.393427e+06,2.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
50%,130.000000,5801.000000,-37.816960,145.010760,2.500946e+06,2.409295e+06,2.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000
75%,169.000000,9999.000000,-37.696102,145.203700,2.517899e+06,2.422651e+06,3.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,2.000000,0.000000,0.000000
max,199.000000,9999.000000,-34.115696,149.757460,2.920148e+06,2.815696e+06,97.000000,48.000000,5.000000,16.000000,...,8.000000,5.000000,3.000000,3.000000,5.000000,21.000000,4.000000,19.000000,9.000000,2.000000

In [44]:
df_vehicle.describe()

,VEHICLE_YEAR_MANUF,VEHICLE_DCA_CODE,ROAD_SURFACE_TYPE,VEHICLE_POWER,VEHICLE_TYPE,VEHICLE_WEIGHT,NO_OF_WHEELS,NO_OF_CYLINDERS,SEATING_CAPACITY,TARE_WEIGHT,TOTAL_NO_OCCUPANTS,CARRY_CAPACITY,CUBIC_CAPACITY,DRIVER_INTENT,VEHICLE_MOVEMENT,CAUGHT_FIRE,LAMPS,LEVEL_OF_DAMAGE,TOWED_AWAY_FLAG,TRAFFIC_CONTROL
count,333775.000000,339867.000000,340712.000000,0.0,340713.000000,42832.000000,297854.000000,305255.000000,281952.000000,328760.000000,340690.000000,42671.000000,47317.000000,340709.000000,340707.000000,340712.00000,340712.000000,340713.000000,340710.000000,340710.000000
mean,1835.854471,2.014865,1.146179,NaN,7.703261,5604.430986,3.898185,4.479799,5.037797,1553.761251,1.245710,2477.383609,1784.203310,7.086223,7.831929,2.03038,2.420763,3.508052,2.030536,5.490760
std,562.382608,1.978917,0.819722,NaN,18.347957,7285.200829,0.680166,1.364208,2.947447,1703.664006,0.837659,4433.489521,1450.798502,18.378423,14.425906,1.12603,2.001220,2.180852,1.997294,18.943729
min,0.000000,1.000000,1.000000,NaN,1.000000,251.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.00000,0.000000,1.000000,1.000000,0.000000
25%,2001.000000,1.000000,1.000000,NaN,1.000000,2495.000000,4.000000,4.000000,5.000000,1100.000000,1.000000,710.000000,600.000000,1.000000,1.000000,2.00000,2.000000,2.000000,1.000000,0.000000
50%,2008.000000,1.000000,1.000000,NaN,2.000000,2840.000000,4.000000,4.000000,5.000000,1400.000000,1.000000,1035.000000,1580.000000,1.000000,2.000000,2.00000,2.000000,3.000000,2.000000,0.000000
75%,2013.000000,2.000000,1.000000,NaN,4.000000,3330.000000,4.000000,6.000000,5.000000,1680.000000,1.000000,1380.000000,2500.000000,3.000000,15.000000,2.00000,2.000000,5.000000,2.000000,1.000000
max,3001.000000,8.000000,9.000000,NaN,99.000000,340000.000000,46.000000,93.000000,74.000000,96000.000000,96.000000,323060.000000,9900.000000,99.000000,99.000000,9.00000,9.000000,9.000000,9.000000,99.000000

# Data preparation

In [45]:
# clean sex column in person dataset
# change from blanks to 'U' for unknown

df_person["SEX"] = df_person["SEX"].replace({"M": "Male",
                                             "F": "Female"})
df_person["SEX"] = df_person["SEX"].fillna("Unknown")
df_person["TAKEN_HOSPITAL"] = df_person["TAKEN_HOSPITAL"].fillna("Not know")
# Code Description CF Centre-front CR Centre-rear D Driver or rider LF Left-front LR Left-rear 
# NA Not applicable NK Not known OR Other-rear PL Pillion passenger PS Motorcycle sidecar passenger RR Right-rear
df_person["SEATING_POSITION"] = df_person["SEATING_POSITION"].replace({"CF": "Centre-front",
                                                                       "CR": "Centre-rear",
                                                                      "D": "Driver or rider",
                                                                      "LF": "Left-front",
                                                                      "LR": "Left-rear",
                                                                      "NA": "Not applicable",
                                                                      "NK": "Not known",
                                                                      "OR": "Other-rear",
                                                                      "PL": "Pillion passenger",
                                                                      "PS": "Motorcycle sidecar passenger",
                                                                      "RR": "Right-rear"})
# Code Description 1 Seatbelt worn 2 Seatbelt not worn 3 Child restraint worn 4 Child restraint not worn 
# 5 Seatbelt/restraint not fitted 6 Crash helmet worn 7 Crash helmet not worn 8 Not appropriate 9 Not known
df_person["HELMET_BELT_WORN"] = df_person["HELMET_BELT_WORN"].replace({1: "Seatbelt worn",
                                                                       2: "Seatbelt not worn",
                                                                      3: "Child restraint worn",
                                                                      4: "Child restraint not worn",
                                                                      5: "Seatbelt/restraint not fitted",
                                                                      6: "Crash helmet worn",
                                                                      7: "Crash helmet not worn",
                                                                      8: "Not appropriate",
                                                                      9: "Not known"})

df_person["EJECTED_CODE"] = df_person["EJECTED_CODE"].replace("9", None)
# df_person["AGE_GROUP"] = df_person["AGE_GROUP"].replace("5/12/2025", "Unknown")
df_person["TAKEN_HOSPITAL"] = df_person["TAKEN_HOSPITAL"].replace("Y", "Yes").replace("N", "No")

# A Australian Capital Territory B Commonwealth D Northern Territory 
# N New South Wales O Overseas Q Queensland S South Australia T Tasmania 
# V Victoria W Western Australia Z Not known _ Not available (Blank value entered)

df_person["LICENCE_STATE"] = df_person["LICENCE_STATE"].replace({"A": "Australian Capital Territory",
                                                                 "B": "Commonwealth",
                                                                "D": "Northern Territory",
                                                                "N": "New South Wales",
                                                                "O": "Overseas",
                                                                "Q": "Queensland",
                                                                "S": "South Australia",
                                                                "T": "Tasmania",
                                                                "V": "Victoria",
                                                                "W": "Western Australia",
                                                                "Z": "Not known"})

# cleaned person dataset
cleaned_person = df_person
cleaned_person.head(20)
# cleaned_person.to_csv('cleaned_person.csv', index=False)

,ACCIDENT_NO,PERSON_ID,VEHICLE_ID,SEX,AGE_GROUP,INJ_LEVEL,INJ_LEVEL_DESC,SEATING_POSITION,HELMET_BELT_WORN,ROAD_USER_TYPE,ROAD_USER_TYPE_DESC,LICENCE_STATE,TAKEN_HOSPITAL,EJECTED_CODE
0,T20120028483,B,B,Male,22-25,3,Other injury,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Not know,0.0
1,T20160009588,03,A,Female,22-25,3,Other injury,Left-rear,Seatbelt worn,3,Passengers,NaN,Not know,0.0
2,T20190007195,A,A,Male,18-21,4,Not injured,Driver or rider,Seatbelt worn,2,Drivers,Not known,Not know,0.0
3,T20190010235,B,B,Male,30-39,3,Other injury,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Not know,NaN
4,T20130004323,01,A,Male,0-4,3,Other injury,Left-rear,Child restraint worn,3,Passengers,NaN,No,0.0
5,T20140003694,B,B,Male,40-49,3,Other injury,Driver or rider,Crash helmet worn,6,Bicyclists,NaN,No,1.0
6,T20160000492,A,A,Female,18-21,3,Other injury,Driver or rider,Seatbelt worn,2,Drivers,Victoria,No,0.0
7,T20160023083,B,B,Male,70+,4,Not injured,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Not know,0.0
8,T20200011739,A,A,Male,30-39,3,Other injury,Driver or rider,Not known,2,Drivers,Victoria,Not know,9.0
9,T20220007151,01,B,Female,22-25,3,Other injury,Left-front,Seatbelt worn,3,Passengers,NaN,Not know,NaN
10,T20250000201,02,B,Female,5-12,3,Other injury,Left-rear,Child restraint worn,3,Passengers,NaN,No,0.0
11,T20130014345,B,B,Male,65-69,4,Not injured,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Not know,0.0
12,T20130017130,A,A,Female,22-25,4,Not injured,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Not know,0.0
13,T20160024067,A,A,Male,22-25,3,Other injury,Driver or rider,Not known,6,Bicyclists,Victoria,No,1.0
14,T20150011488,01,B,Female,50-59,4,Not injured,Left-front,Seatbelt worn,3,Passengers,NaN,Not know,0.0
15,T20190011669,A,A,Female,18-21,3,Other injury,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Not know,0.0
16,T20220011677,B,B,Female,18-21,3,Other injury,Driver or rider,Not known,2,Drivers,Victoria,Not know,0.0
17,T20230026003,A,A,Female,70+,2,Serious injury,Driver or rider,Seatbelt worn,2,Drivers,Victoria,Yes,0.0
18,T20120028931,A,A,Female,40-49,3,Other injury,Driver or rider,Seatbelt worn,2,Drivers,Victoria,No,0.0
19,T20130017914,01,A,Female,16-17,3,Other injury,Left-front,Seatbelt worn,3,Passengers,NaN,No,0.0

In [52]:
# clean vehicle dataset

# Code Description E East N North NE North east NW North west S South SE South east SW South west W West NK Not known
df_vehicle["INITIAL_DIRECTION"] = df_vehicle["INITIAL_DIRECTION"].replace({"E": "East",
                                                                        "N": "North",
                                                                       "NE": "North east",
                                                                       "NW": "North west",
                                                                       "S": "South",
                                                                       "SE": "South east",
                                                                       "SW": "South west",
                                                                       "W": "West",
                                                                       "NK": "Not known"})

# delete rows with unexpected values in VEHICLE_YEAR_MANUF
# store between 0 and 2025 only
df_vehicle = df_vehicle[(df_vehicle["VEHICLE_YEAR_MANUF"] >= 0) & (df_vehicle["VEHICLE_YEAR_MANUF"] <= 2025)]
# print(df_vehicle["VEHICLE_YEAR_MANUF"].describe()) # check cleaned year of manufacture

# A Australian Capital Territory B Commonwealth D Northern Territory N New South Wales O Overseas 
# Q Queensland S South Australia T Tasmania V Victoria W Western Australia Z Not known _ (Blank value entered)/Not available

df_vehicle["REG_STATE"] = df_vehicle["REG_STATE"].replace({"A": "Australian Capital Territory",
                                                            "B": "Commonwealth",
                                                             "D": "Northern Territory",
                                                             "N": "New South Wales",
                                                             "O": "Overseas",
                                                             "Q": "Queensland",
                                                             "S": "South Australia",
                                                             "T": "Tasmania",
                                                             "V": "Victoria",
                                                             "W": "Western Australia",
                                                             "Z": "Not known"})

df_vehicle["VEHICLE_BODY_STYLE"] = df_vehicle["VEHICLE_BODY_STYLE"].fillna("Not known")
import pandas as pd

# Dictionary mapping codes to descriptions
code_map = {
    "AFRAME": "A Frame",
    "AG IMP": "Agricultural Implement For Prim.Prod.",
    "AMB": "Ambulance Emergency Vehicle",
    "AMPHIB": "Amphibian Land And Water Craft",
    "AMUS": "Amusement",
    "ARM V": "Armoured Vehicle",
    "B BIN": "Bulk Bin",
    "B HOE": "Back Hoe",
    "B TR": "Boat Trailer",
    "B/TR": "Boat Trailer",
    "BD/PMR": "B Double Prime Mover (Feds Only)",
    "BOX": "Box Trailer",
    "BUGGY": "Buggy Beach Buggy, Golf Buggy",
    "BUS": "Bus Used For Passenger Carriage",
    "C CAR": "Car Carrier Used For Car Carriage",
    "C MIX": "Concrete Mixer",
    "CARAVN": "Caravan",
    "CARVN": "Mobile Caravan Self Propelled Caravan",
    "CHAIR": "Motor Chair Motorized Wheelchair",
    "COMPAC": "Compactor",
    "CONT C": "Container Carrier",
    "CONVRT": "Convertible Car with removable top",
    "COUPE": "Coupe Car With 2 Doors",
    "CRANE": "Mobile Crane",
    "CYCLE": "Motor Cycle",
    "DITCH": "Ditch Witch",
    "DOLLY": "Dolly",
    "DOZER": "Bulldozer",
    "DUMPER": "Dumper",
    "EDUCTR": "Eductor",
    "EXCVTR": "Excavator",
    "F LIFT": "Fork Lift",
    "F UNIT": "Fire Unit",
    "FLOAT": "Moomba Float",
    "FLUSH": "Flusher",
    "FRAME": "Frame",
    "G UNIT": "Garbage Unit",
    "GRADER": "Grader",
    "H FLT": "Horse Float",
    "H/FLT": "Horse Float",
    "HEARSE": "Hearse",
    "HOE B": "Hoe",
    "HOR FL": "Horse Float",
    "IND/CN": "Individual Construction",
    "INDCON": "Individual Construction",
    "JEEP": "Jeep",
    "JINKER": "Jinker",
    "L FRM": "Log Frame (Rigid)",
    "L LOAD": "Low Loader",
    "L MARK": "Line Marker",
    "LADDER": "Ladder Truck",
    "LOADER": "Loader",
    "M BILL": "Mobile Billboard",
    "M CCH": "Mourning Coach",
    "M STDO": "Mobile Studio",
    "M STND": "Mobile Grandstand",
    "MACH": "Machine",
    "MACHNE": "Machine",
    "MISC": "Miscellaneous",
    "MOPED": "Motor Cycle",
    "MOWER": "Mower",
    "MULTI": "Multi",
    "MULTIX": "Multix",
    "OF SHD": "Office Shed",
    "OF/SHD": "Office Shed",
    "OUTFIT": "Motor Cycle",
    "P CARR": "Personnel Carrier",
    "P MVR": "Prime Mover",
    "P VAN": "Panel Van",
    "PMAMUS": "Prime Mover Amusement",
    "R AMUS": "Rigid Amusement",
    "RDSTR": "Roadster Convertible with 2 seats",
    "RLINER": "Road Liner",
    "ROLLER": "Roller",
    "S AMB": "Semi Ambulance",
    "S AMRV": "Semi Armoured Vehicle",
    "S AMUS": "Semi Amusement Vehicle",
    "S BULK": "Semi Bulk Bin",
    "S CAR": "Semi Car Carrier",
    "S CONT": "Semi Container Carrier",
    "S CRVN": "Semi Mobile Caravan",
    "S DCMP": "Semi Decompression Chamber",
    "S FLSH": "Semi Flusher",
    "S FLT": "Semi Float",
    "S FRM": "Semi Frame",
    "S JINK": "Semi Timber Jinker",
    "S LOAD": "Semi Loader",
    "S MACH": "Semi Machine",
    "S SERV": "Semi Service",
    "S SPRD": "Semi Lime Spreader",
    "S SPRY": "Semi Sprayer",
    "S TANK": "Semi Tanker",
    "S TRL": "Semi Trailer",
    "S TTWR": "Semi Travel Tower",
    "S VAN": "Semi Trailer Van",
    "S WAG": "Station Wagon Car With Internal Boot",
    "SCOOP": "Shovel",
    "SCOOTR": "Scooter",
    "SED": "Sedan - Car with external boot",
    "SEDAN": "Sedan - Car with external boot",
    "SWV1": "Quad Bike",
    "SWV2": "4 Wheel Drive – All Terrain Vehicle"
}

# Replace codes with descriptions
df_vehicle['VEHICLE_BODY_STYLE'] = df_vehicle['VEHICLE_BODY_STYLE'].replace(code_map)


# Manufacturer code-to-description mapping
make_map = {
    "AEC": "A E C",
    "ALBION": "Albion",
    "ALFA R": "Alfa Romeo",
    "ALLARD": "Allard",
    "ALLIS": "Allis",
    "ANSAIR": "Ansair",
    "ASI": "A S I",
    "ASIA": "Asia",
    "ASTON": "Aston Martin",
    "ATHEY": "Athey",
    "ATKINS": "Atkinson",
    "AUDI": "Audi",
    "AUSTIN": "Austin",
    "AUSTRL": "Austral",
    "B KNOX": "Blaw Knox",
    "BED": "Bedford",
    "BED IS": "Bedford Isuzu",
    "BELARS": "Belarus",
    "BENFRD": "Benford",
    "BENT": "Bentley",
    "BERL": "Berliet",
    "BHB": "B H B",
    "BMW": "B M W",
    "BOMBDR": "Bombardier",
    "BSA": "B S A",
    "BUICK": "Buick",
    "CAD": "Cadillac",
    "CASE": "Case",
    "CATPLR": "Caterpillar",
    "CHAMB": "Chamberlain",
    "CHAMP": "Champion",
    "CHEV": "Chevrolet",
    "CHRYS": "Chrysler",
    "CITRN": "Citroen",
    "COLES": "Coles",
    "COMMER": "Commer",
    "CONQ": "Conquip",
    "CUMMIN": "Cummins",
    "D BRN": "David Brown",
    "DAEWOO": "Daewoo",
    "DAF": "D A F",
    "DAIHAT": "Diahatsu",
    "DAIM": "Daimler",
    "DATSUN": "Datsun",
    "DENING": "Denning",
    "DENNIS": "Dennis",
    "DETOM": "Detomaso",
    "DEUTZ": "Deutz",
    "DIA R": "Diamond Reo",
    "DIA T": "Diamond T",
    "DIAMON": "Diamond",
    "DIATTO": "Diatto",
    "DODGE": "Dodge",
    "DOMINO": "Domino",
    "DYNAPC": "Dynapac",
    "ENFLD": "Enfield",
    "ERF": "E R F",
    "ESSEX": "Essex",
    "EUNOS": "Eunos500",
    "EUREKA": "Eureka",
    "F LINE": "Freightliner",
    "FENDT": "Fendt",
    "FERG": "Ferguson",
    "FERRAR": "Ferrari",
    "FIAT": "Fiat",
    "FMC": "F M C",
    "FORD": "Ford",
    "FORDSN": "Fordson",
    "FRANNA": "Franna",
    "FRGHTR": "Freighter-Lawton",
    "FRMLNR": "Farmliner",
    "FSM": "F S M",
    "FUJI": "Fuji",
    "FURUKA": "Furukawa",
    "GALANT": "Galant (Chrysler)",
    "GALION": "Galion",
    "GMC": "G M C",
    "GRAD": "Gradall",
    "H COCK": "Hancock",
    "H DAV": "Harley Davidson",
    "H MADE": "Homemade",
    "HAFL": "Haflinger",
    "HANOM": "Hanomag",
    "HILL": "Hillman",
    "HITACH": "Hitachi",
    "HOLDEN": "Holden",
    "HSQVRN": "Husqvarna",
    "HUST": "Hustler",
    "HYNDAI": "Hyundai",
    "HYSTER": "Hyster",
    "I RAND": "Ingerson Rand",
    "INTERN": "International",
    "ISEKI": "Iseki",
    "ISUZU": "Isuzu",
    "J DEER": "John Deere",
    "JAGUAR": "Jaguar",
    "JBJ": "J B J",
    "JCB": "J C B",
    "JEEP": "Jeep",
    "JENSEN": "Jensen",
    "KATO": "Kato",
    "KAWASA": "Kawasaki",
    "KENWTH": "Kenworth",
    "KIA": "Kia",
    "L ROV": "Land Rover",
    "LADA": "Lada",
    "LOTUS": "Lotus",
    "MAZDA": "Mazda",
    "MERC B": "Mercedes-Benz",
    "NISSAN": "Nissan",
    "OLDS": "Oldsmobile",
    "PEUGEOT": "Peugeot",
    "PONT": "Pontiac",
    "PORSCH": "Porsche",
    "R ROV": "Range Rover",
    "RAMBLR": "Rambler",
    "REN": "Renault",
    "ROLLS": "Rolls-Royce",
    "ROVER": "Rover",
    "SAAB": "Saab",
    "SUBARU": "Subaru",
    "SUZUKI": "Suzuki",
    "TOYOTA": "Toyota",
    "VOLKS": "Volkswagen",
    "VOLVO": "Volvo",
    "YAMAHA": "Yamaha"
}

df_vehicle['VEHICLE_MAKE'] = df_vehicle['VEHICLE_MAKE'].replace(make_map)
df_vehicle.head(20)

,ACCIDENT_NO,VEHICLE_ID,VEHICLE_YEAR_MANUF,VEHICLE_DCA_CODE,INITIAL_DIRECTION,ROAD_SURFACE_TYPE,ROAD_SURFACE_TYPE_DESC,REG_STATE,VEHICLE_BODY_STYLE,VEHICLE_MAKE,...,TRAILER_TYPE,VEHICLE_COLOUR_1,VEHICLE_COLOUR_2,CAUGHT_FIRE,INITIAL_IMPACT,LAMPS,LEVEL_OF_DAMAGE,TOWED_AWAY_FLAG,TRAFFIC_CONTROL,TRAFFIC_CONTROL_DESC
1,T20120002094,C,1997.0,8.0,West,1.0,Paved,Victoria,Sedan - Car with external boot,MITSUB,...,H,RED,ZZ,2.0,5,2.0,1,2.0,0.0,No control
2,T20120002390,A,2001.0,1.0,North east,3.0,Gravel,Victoria,Sedan - Car with external boot,Holden,...,H,GRY,ZZ,2.0,F,9.0,1,2.0,0.0,No control
4,T20120010082,B,2005.0,2.0,South,1.0,Paved,Victoria,Sedan - Car with external boot,Toyota,...,H,SIL,ZZ,2.0,R,2.0,4,1.0,1.0,Stop-go lights
5,T20120011153,B,2007.0,2.0,North west,1.0,Paved,Queensland,Sedan - Car with external boot,Nissan,...,H,YLW,ZZ,2.0,5,2.0,3,1.0,0.0,No control
7,T20120014395,A,2007.0,1.0,North west,1.0,Paved,Victoria,Sedan - Car with external boot,Ford,...,H,YLW,ZZ,2.0,7,1.0,4,1.0,0.0,No control
8,T20120014749,A,2008.0,2.0,South,1.0,Paved,Victoria,Sedan - Car with external boot,HONDA,...,H,BLK,ZZ,2.0,R,2.0,2,2.0,1.0,Stop-go lights
9,T20120014996,A,1996.0,1.0,South,1.0,Paved,Victoria,Sedan - Car with external boot,Ford,...,H,BLU,ZZ,2.0,5,2.0,1,2.0,0.0,No control
10,T20120016533,B,1987.0,2.0,West,1.0,Paved,Victoria,Sedan - Car with external boot,Holden,...,H,RED,ZZ,2.0,2,0.0,3,1.0,0.0,No control
11,T20120019585,A,2003.0,1.0,North,1.0,Paved,Victoria,WAGON,MITSUB,...,H,SIL,ZZ,2.0,F,2.0,2,2.0,11.0,Giveway sign
12,T20120020097,A,1995.0,1.0,East,1.0,Paved,Victoria,Sedan - Car with external boot,Toyota,...,H,BLU,ZZ,2.0,3,2.0,2,2.0,0.0,No control
13,T20120020876,A,1998.0,1.0,North,1.0,Paved,Victoria,WAGON,Toyota,...,H,BRN,ZZ,2.0,N,2.0,6,9.0,0.0,No control
14,T20120021884,B,2006.0,8.0,East,1.0,Paved,Victoria,TRAY,MITSUB,...,H,YLW,ZZ,2.0,1,2.0,1,2.0,0.0,No control
15,T20120022840,B,2002.0,1.0,East,1.0,Paved,Victoria,Sedan - Car with external boot,Holden,...,H,BLK,ZZ,2.0,6,2.0,2,2.0,0.0,No control
17,T20120023426,B,2007.0,2.0,West,1.0,Paved,Victoria,SOLO,HYOSUN,...,H,SIL,ZZ,2.0,F,2.0,3,1.0,0.0,No control
19,T20120024426,C,2003.0,8.0,West,1.0,Paved,Victoria,Sedan - Car with external boot,Kia,...,H,GRY,ZZ,2.0,R,2.0,1,2.0,0.0,No control
20,T20120024522,A,2007.0,2.0,South east,1.0,Paved,Victoria,Bus Used For Passenger Carriage,SCANIA,...,H,WHI,ZZ,2.0,5,2.0,2,2.0,15.0,Other
21,T20120025552,A,1999.0,1.0,East,1.0,Paved,Victoria,Sedan - Car with external boot,Ford,...,H,GRN,ZZ,2.0,F,1.0,4,1.0,0.0,No control
22,T20120027001,A,1998.0,1.0,South,1.0,Paved,Victoria,SOLO,HONDA,...,H,BLK,ZZ,2.0,N,0.0,1,2.0,0.0,No control
23,T20120028516,B,2006.0,1.0,South east,3.0,Gravel,Victoria,TIPPER,Freightliner,...,L,WHI,ZZ,2.0,F,2.0,2,2.0,0.0,No control
24,T20130000413,A,2009.0,1.0,North,3.0,Gravel,Victoria,SOLO,K T M,...,H,OGE,BLK,2.0,F,1.0,1,2.0,0.0,No control